<div class="top-container">
    <header>
        <nav id="menu">
            <ul>
                <li><a href="cliente">Software EmpregaBR</a></li>
                <li><a href="cliente">Home</a></li>
                <li><a href="cliente/curriculo">Curriculo</a></li>
                <li><a href="cliente/vaga">Vagas</a></li>
                <li><a href="cliente/processoseletivo">Processos Seletivos</a></li>
                <li><a href="cliente/historico">Histórico</a></li>
                <li><a href="cliente/conta">Conta</a></li>
                <li><a href="logout">Logout</a></li>
            </ul>
        </nav>
        
    </header>

    <article>
        <?php $this->controller->renderView(); ?>
    </article>
</div>
<footer class="bottom-container">
    <p>EmpregaBR - Recrutamento e Seleção</p>
    <h5>Último acesso ao Sistema realizado em: <?php echo date('d/m/Y H:i', strtotime($data)) ?></h5>
</footer>