<!DOCTYPE html>
<html lang="en">
        <head>
                <base href="/localhost" />
                <meta charset="UTF-8" />
                <title><?= $title ?></title>
                <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans" rel="stylesheet">
                <link rel="stylesheet" href="../assets/css/style.css" type="text/css"/>
                <script type="text/javascript" src="../assets/js/jquery-3.2.1.min.js"></script>
                <script type="text/javascript" src="../assets/js/js.js"></script>
        </head>

        <body>
                <?php $this->controller->renderView(); ?>
                
        </body>
</html>
