<div class="top-container">
    <header id="menu_empresa">
        <nav id="menu">
            <ul>
                <li><a href="empresa">Software EmpregaBR</a></li>
                <li><a href="empresa">Home</a></li>
                <li><a href="empresa/empresa-candidato">Candidatos</a></li>
                <li><a href="empresa/vaga">Vagas</a></li>
                <li><a href="empresa/processo-seletivo">Processos Seletivos</a></li>
                <li><a href="empresa/usuario">Usuários</a></li>
                <li><a href="empresa/conta">Conta</a></li>
                <li><a href="logout">Logout</a></li>
            </ul>
        </nav>
        
    </header>
    
    <article>
        <?php $this->controller->renderView(); ?>
    </article>
</div>
<footer class="bottom-container">
    <p>EmpregaBR - Recrutamento e Seleção</p>
</footer>

