
<form method="POST" id="form-register" class="login-container">
    <h1>Login do Sistema</h1>
    <input type="text" name="login" required placeholder="Nome: ">
    <input type="password" name="senha" required placeholder="Senha: ">
    <input type="submit" value="Logar">
    <?php if(!empty($error)){?>
    <div class="error"><?php echo $error ?></div>
    <?php } ?>
</form> 

<a href="register">Registrar</a>