<h1>Pagina Register</h1>
<form method="POST" id="form-register">
    <input type="text" name="login" required placeholder="Login: ">
    <input type="password" name="senha" required placeholder="Senha: "><br>
    <input type="radio" name="level" value="1" checked> Cliente<br>
    <input type="radio" name="level" value="2"> Empresa<br>
    <input type="submit" value="Registrar">
    <div class="error"><?= $error ?></div>
</form>