<table class="table table-striped table-bordered">
    </br></br></br>
    <tr>
        <td align="center">ID Candidato</td>
        <td align="center">Nome</td>
        <td align="center">CPF</td>
        <td align="center">E-mail</td>
        <td align="center">ID Usuário</td>
        <td align="center">Ações</td>
    </tr>
    
    <?php if ($candidatos) {
        foreach ($candidatos as $c){?>
            <tr>
                <td align="center"><?= $c['Id_candidato']?></td>
                <td><?= $c['nome'] ?></td>
                <td align="center"><?= $c['cpf'] ?></td>
                <td align="center"><?= $c['email'] ?></td>
                <td align="center"><?= $c['FK_Id_user'] ?></td>
                <td align="center">
                    <button class="candidatar btn btn-primary" value="<?= $c['Id_candidato'] ?>">
                        Editar
                    </button>
                    <button class="candidatar btn btn-primary" value="<?= $c['Id_candidato'] ?>">
                        Remover
                    </button>
                    
                </td>
            </tr>
            <?php
        }
    }else {
        echo "<tr>" . "No momento não há vagas Disponíveis para estas Areas de Interesse" . "</tr>";
    }?>	
</table>

<br><br>