<h1 class="title">Candidatos</h1>

<div class="dados">
    <form>
        <div>
            <div><span>Filtrar por:</span>
            <select name="opcaofiltro">
                    <option value="1">Nome</option>
                    <option value="2">Localidade</option>
                    <option value="3">Data de Cadastro</option>
            </select></div>
            <div><span>Pesquisa:</span><input type="text" name="filtro" required placeholder="Digite aqui sua busca... "></div>
        </div>
        <div class="center-content">
            <button>Pesquisar</button>
        </div>
    </form>
</div>

<?php if (!empty($candidatos)) { ?>
<div class="overflow-x">
    <table class="tabela">
        <tr>
            <th>ID Candidato</th>
            <th>Nome</th>
            <th>CPF</th>
            <th>E-mail</th>
            <th>Data Nascimento</th>
            <th>Cidade</th>
            <th>Estado</th>
            <th>Ações</th>
        </tr>
    <?php
        foreach ($candidatos as $c){?>
            <tr>
                <td><?= $c['Id_candidato']?></td>
                <td><?= $c['nome_completo'] ?></td>
                <td><?= $c['cpf'] ?></td>
                <td><?= $c['email'] ?></td>
                <td><?= $c['data_nascimento'] ?></td>
                <td><?= $c['cidade'] ?></td>
                <td><?= $c['estado'] ?></td>
                <td>
                    <form method="POST">
                        <button name="detalhesTemp" value="<?php echo $c['Id_candidato'] ?>">Visualizar Curriculo em PDF</button>
                    </form>
                </td>
            </tr>
            <?php
        } ?>

    </table>
</div>
    <?php }else { ?>
        <p>No momento não há candidatos no sistema</p>
    <?php }?>	