<h3><?php echo $dadosconta['razaoSocial']; ?></h3>
<h3>Alterar Informações de Meu Perfil de Acesso</h3>
<form method="POST" enctype="multipart/form-data">
  <label>Foto:</label>
  <input type="file" name="foto" />
  <input type="submit" value="Salvar" />
</form>

<button class="newVaga" id="alterarSenha">Alterar Senha</button>
<form method="POST" id="alterarSenha" class="container">
    Razão Social: <input type="text" name="nome" required placeholder="<?php echo $dadosconta['razaoSocial'] ?>" disabled>
    Nome Fantasia: <input type="text" name="nome" required placeholder="<?php echo $dadosconta['nomeFantasia'] ?>" disabled>
    E-mail: <input type="text" name="email" required placeholder="<?php echo $dadosconta['email'] ?>" disabled>
    CNPJ: <input type="text" name="cpf" required placeholder="<?php echo $dadosconta['cnpj'] ?>" disabled>
    Nova Senha:<input type="password" name="password" required placeholder="Insira sua nova Senha... ">
    Confirme a Senha:<input type="password" name="password" required placeholder="Confirme sua nova Senha... ">
    <button>Salvar Alterações</button>
</form>