<h1 class="title">Dados da Empresa</h1>

<div class="inform">
    <p><b>Razão Social:</b> <?php echo $dadosconta['razaoSocial'] ?></p>
    <p><b>Nome Fantasia:</b> <?php echo $dadosconta['nomeFantasia'] ?></p>
    <p><b>CNPJ:</b> <?php echo $dadosconta['cnpj'] ?></p>
    <p><b>Inscrição Estadual:</b> <?php echo $dadosconta['ie'] ?></p>
    <p><b>Ramo de Atuação da Empresa:</b> <?php echo $dadosconta['ramoEmpresa'] ?></p>
    <p><b>Endereço:</b> <?php echo $dadosconta['endereco'] ?></p>
    <p><b>Bairro:</b> <?php echo $dadosconta['bairro'] ?></p>
    <p><b>Cidade:</b> <?php echo $dadosconta['cidade'] ?> - <b>Estado:</b> <?php echo $dadosconta['estado'] ?></p>
    <p><b>Telefone Comercial:</b> <?php echo $dadosconta['telefonecomercial'] ?></p>
    <p><b>E-mail:</b> <?php echo $dadosconta['email'] ?></p>
</div>

<div class="center-content">
    <button class="newVaga" id="alterarSenhaAcesso">Alterar Senha de Acesso</button></a>
</div>
<div class="dados">
    <form method="POST" id="alterarSenhaAcesso" class="container-hidden">
        <div>
            <input type="hidden" name="nome" required placeholder="<?php echo $dadosconta['razaoSocial'] ?>" disabled>
            <input type="hidden" name="nome" required placeholder="<?php echo $dadosconta['nomeFantasia'] ?>"disabled>
            <input type="hidden" name="email" required placeholder="<?php echo $dadosconta['email'] ?>"disabled>
            <input type="hidden" name="cpf" required placeholder="<?php echo $dadosconta['cnpj'] ?>"disabled>
            <div><span>Nova Senha:</span><input type="password" name="password" required placeholder="Insira sua nova Senha... "></div>
            <div><span>Confirme a Senha:</span><input type="password" name="password" required placeholder="Confirme sua nova Senha... "></div>
        </div>
        <div class="center-content">
            <button>Salvar Nova Senha</button>
        </div>
    </form>
</div>

<div class="center-content">
    <button class="newVaga" id="alterarDadosEmpresa">Alterar Dados da Empresa</button></a>
</div>
<div class="dados">
    <form method="POST" id="alterarDadosEmpresa" class="container-hidden">
        <div>
            <div><span>Razão Social:</span><input type="text" name="nome" required placeholder="<?php echo $dadosconta['razaoSocial'] ?>"></div>
            <div><span>Nome Fantasia:</span><input type="text" name="nome" required placeholder="<?php echo $dadosconta['nomeFantasia'] ?>"></div>
            <div><span>E-mail:</span><input type="text" name="email" required placeholder="<?php echo $dadosconta['email'] ?>"></div>
            <div><span>CNPJ:</span><input type="text" name="cpf" required placeholder="<?php echo $dadosconta['cnpj'] ?>"></div>
            <div><span>Nova Senha:</span><input type="password" name="password" required placeholder="Insira sua nova Senha... "></div>
            <div><span>Confirme a Senha:</span><input type="password" name="password" required placeholder="Confirme sua nova Senha... "></div>
        </div>
        <div class="center-content">
            <button>Salvar Alterações</button>
        </div>
    </form>
</div>