<?php
    echo "ID Empresa: ".$dadosconta['ID_empresa']."<br>";
    echo "Razão Social: ".$dadosconta['razaoSocial']."<br>";
    echo "Nome Fantasia: ".$dadosconta['nomeFantasia']."<br>";
    echo "CNPJ: ".$dadosconta['cnpj']."<br>";
    echo "Inscrição Estadual: ".$dadosconta['ie']."<br>";
    echo "Ramo de Atuação da Empresa: ".$dadosconta['ramoEmpresa']."<br>";
    echo "Endereço: ".$dadosconta['endereco']."<br>";
    echo "Bairro: ".$dadosconta['bairro']."<br>";
    echo "Cidade: ".$dadosconta['cidade']." - Estado: ".$dadosconta['estado']."<br>";
    echo "Telefone Comercial: ".$dadosconta['telefonecomercial']."<br>";
    echo "E-mail: ".$dadosconta['email']."<br>";
    echo "Empresa Ativa: ".$dadosconta['confirmado']."<br>";
    echo "ID Usuário: ".$dadosconta['FK_Id_user']."<br>";
?>

<button align=center class="newVaga" id="alterarSenhaAcesso">Alterar Senha de Acesso</button><br><br></a>
<form align=center method="POST" id="alterarSenhaAcesso" class="container">
    Razão Social: <input type="text" name="nome" required placeholder="<?php echo $dadosconta['razaoSocial'] ?>" disabled>
    <br>Nome Fantasia: <input type="text" name="nome" required placeholder="<?php echo $dadosconta['nomeFantasia'] ?>"disabled>
    <br>E-mail: <input type="text" name="email" required placeholder="<?php echo $dadosconta['email'] ?>"disabled>
    <br>CNPJ: <input type="text" name="cpf" required placeholder="<?php echo $dadosconta['cnpj'] ?>"disabled>
    <br>Nova Senha:<input type="password" name="password" required placeholder="Insira sua nova Senha... ">
    <br>Confirme a Senha:<input type="password" name="password" required placeholder="Confirme sua nova Senha... ">
    <br><br><button>Salvar Nova Senha</button>
    <br>
    <br>
    <br>
</form>


<button align=center class="newVaga" id="alterarDadosEmpresa">Alterar Dados da Empresa</button><br><br></a>
<form align=center method="POST" id="alterarDadosEmpresa" class="container">
    Razão Social: <input type="text" name="nome" required placeholder="<?php echo $dadosconta['razaoSocial'] ?>">
    <br>Nome Fantasia: <input type="text" name="nome" required placeholder="<?php echo $dadosconta['nomeFantasia'] ?>">
    <br>E-mail: <input type="text" name="email" required placeholder="<?php echo $dadosconta['email'] ?>">
    <br>CNPJ: <input type="text" name="cpf" required placeholder="<?php echo $dadosconta['cnpj'] ?>">
    <br>Nova Senha:<input type="password" name="password" required placeholder="Insira sua nova Senha... ">
    <br>Confirme a Senha:<input type="password" name="password" required placeholder="Confirme sua nova Senha... ">
    <br><br><button>Salvar Alterações</button>
    <br>
    <br>
    <br>
</form>