<h2 class="title">Dashboard Empresa</h2>

<div id="feedback">
    <h2>Processos Seletivos Pendentes</h2>
    <div>
        <?php
            foreach($processosSeletivosAbertos as $psa){
                echo "<div>";
                echo "<p>Processo Seletivo Nº: ".$psa['ID_processoseletivo']." - Status :".$psa['status']." - Vagas Restantes: ".$psa['vagasrestantes']."</p>";
                echo "</div>";
            }
        ?>
    </div>
    <form method="POST">
        <button name="+processosseletivos">Veja Mais...</button>
    </form>
</div>
<div id="indique">
    <h2>Vagas Abertas Recentemente</h2>
    <div>
        <?php
            foreach($vagasAbertas as $va){
                echo "<div>";
                echo "<p>Vaga Nº: ".$va['ID_vaga']." - Cargo: ".$va['cargo']. "</p>";
                echo "<p>Qtde. Vagas: ".$va['qtdeVagas']." - Data de Cadastro: ".$va['dataCadastro']. "</p>";
                echo "</div>";
            }
        ?>
    </div>
    <form method="POST">
        <button name="+vagas">Veja Mais...</button>
    </form>
    </div>
<div class="indicacao">
    <button>Indique nossa Ferramenta para um Parceiro</button>
</div>