<h2 align="center"><br>Dashboard Empresa<br></h2>

<?php
echo "<br>Level: ".$_SESSION['level']."<br>";
echo "Id da Empresa:".$_SESSION['Id_empresa'];
?>

<div align="center" id="feedback">
    <h2 align=center>Processos Seletivos Pendentes</h2>
    <br>
    <?php
        foreach($processosSeletivosAbertos as $psa){
            echo "Processo Seletivo Nº: ".$psa['ID_processoseletivo']." - Status :".$psa['status']." - Vagas Restantes: ".$psa['vagasrestantes']."<br>";
        }
    ?>
    <br>
    <form method="POST">
        <button name="+processosseletivos">Veja Mais...</button><br><br>
    </form>
</div>
<br>
<div id="indique" align="center">
    <h2 align=center>Vagas Abertas Recentemente</h2>
    <br>
    <?php
        foreach($vagasAbertas as $va){
            echo "Vaga Nº: ".$va['ID_vaga']." - Cargo: ".$va['cargo']."<br>";
            echo "Qtde. Vagas: ".$va['qtdeVagas']." - Data de Cadastro: ".$va['dataCadastro']."<br><br>";
        }
    ?>
    <br>
    <form method="POST">
        <button name="+vagas">Veja Mais...</button><br><br>
    </form>
    </div>
<br>
<button align="center">Indique nossa Ferramenta para um Parceiro</button>
<br>
<br>