<h2>Página de Nova Vaga</h2>

<form method="POST">
Área de Interesse:
<input type="text" name="areaInteresse" required placeholder="Nome... "><br>

Cargo:
<input type="text" name="areaInteresse" required placeholder="Nome... "><br>

Descrição:
<input type="text" name="areaInteresse" required placeholder="Nome... "><br>

Qtde. Vagas:
<input type="text" name="areaInteresse" required placeholder="Nome... "><br>

Horário Trabalho:
<input type="text" name="areaInteresse" required placeholder="Nome... "><br>

Tipo de Contrato:
<input type="text" name="areaInteresse" required placeholder="Nome... "><br>

Salário:
<input type="text" name="areaInteresse" required placeholder="Nome... "><br>

Detalhes Vaga:
<input type="text" name="areaInteresse" required placeholder="Nome... "><br>

Data de Cadastro:
<input type="text" name="areaInteresse" required placeholder="Nome... "><br>

Status Vaga:
<input type="text" name="areaInteresse" required placeholder="Nome... "><br>


    <button name="Salvar" value="Salvar">Salvar Vaga</button><br><br></a>
</form>

