<h1 class="title">Processos Seletivos</h1>
<?php if(!empty($processosSeletivos)){ ?>
    <div class="overflow-x">
        <table class="tabela">
            <tr>
                <th>ID</th>
                <th>Vaga</th>
                <th>Status</th>
                <th>Qtde. Vagas</th>
                <th>Empresa</th>
                <th colspan="5">Ações</th>
                <th class="adicionar">Adicionar</th>
            </tr>
    
        <?php foreach($processosSeletivos as $ps){ ?>
            <tr align="center">
                <td><?php echo $ps['ID_processoseletivo'] ?></td>
                <td><?php echo $ps['cargo'] ?></td>
                <td><?php echo $ps['status'] ?></td>
                <td><?php echo $ps['vagasrestantes'] ?></td>
                <td><?php echo $ps['FK_Id_empresa'] ?></td>
            <!--<td class="editar"><?php //echo $v['ID_vaga'] ?></td>
            <td class="editar">Editar</td>
            <td class="deletar"><?php //echo $v['ID_vaga'] ?></td>
            <td class="deletar">Deletar</td>-->
            
                <td>
                    <form method="POST">
                        <button name="etapa01" <?php if ($ps['status']=='C'){ echo 'disabled '; echo "class='disabled'";} ?> value='<?php echo $ps['ID_processoseletivo'] ?>'>Etapa 01</button>
                    </form>
                </td>
                <td>
                    <form method="POST">
                        <button name="etapa02" <?php if ($ps['status']=='C'){ echo 'disabled '; echo "class='disabled'";} ?> value='<?php echo $ps['ID_processoseletivo'] ?>'>Etapa 02</button>
                    </form>
                </td>
                <td>
                    <form method="POST">
                        <button name="etapa03" <?php if ($ps['status']=='C'){ echo 'disabled '; echo "class='disabled'";} ?> value='<?php echo $ps['ID_processoseletivo'] ?>'>Etapa 03</button>
                    </form>
                </td>
                <td>
                    <form method="POST">
                        <button name="etapa04" <?php if ($ps['status']=='C'){ echo 'disabled '; echo "class='disabled'";} ?> value='<?php echo $ps['ID_processoseletivo'] ?>'>Contratados</button>
                    </form>
                </td>
                <td>
                    <form method="POST">
                        <button name="detalhesTemp" <?php if ($ps['status']=='C'){ echo 'disabled '; echo "class='disabled'";} ?> value="<?php echo $ps['ID_processoseletivo'] ?>">Enviar Feedback</button>
                    </form>
                </td>
                <td>
                    <form method="POST">
                        <button name="filtro_processocandidato" <?php if ($ps['status']=='C'){ echo 'disabled '; echo "class='disabled'";} ?> value="<?php echo $ps['ID_processoseletivo'] ?>">Vincular Candidatos</button>
                    </form>
                </td>
            </tr>
    <?php } ?>
    </table>
</div>
<?php } ?>
<div class="center-content">
    <button class="newVaga" id="inserirProcessoSeletivo" value="novo">Novo Processo Seletivo</button>
</div>
<div class="dados">
    <form method="POST" id="inserirProcessoSeletivo" class="container-hidden">
        <div>
            <div><span>Vaga:</span><select name="vaga">
                <?php 
                    foreach ($vagaspendentes as $v) {?>
                        <option value="<?php echo $v['ID_vaga']?>"><?php echo $v['cargo'] ?></option>    
                    <?php }
                ?>
            </select></div>
            <div><span>Status:</span><select name="status">
                <option value="A">Aguardando Inicio</option>
                <option value="CC">Fase de Cadastramento Currículos</option>
                <option value="AC">Análise dos Candidatos</option>
                <option value="PA">Processo em Andamento</option>
                <option value="P">Pausado</option>
                <option value="C">Concluído</option>
            </select></div>
        </div>
        <div class="center-content">
            <input type="submit" value="Salvar">
        </div>
    </form>
</div>