<h1 class="title">Vaga <?php echo $vaga['cargo'] ?></h1>
<div class="template">
    <p><b>Vaga Nº:</b> <?php echo $id ?></p>
    <p><b>Vaga:</b> <?php echo $vaga['cargo'] ?></p>
    <p><b>Área de Interesse:</b> <?php echo $vaga['areainteresse'] ?></p>
    <p><b>Descrição da Vaga:</b> <?php echo $vaga['descricao'] ?></p>
    <p><b>Quantidade de Vagas Disponíveis:</b> <?php echo $vaga['qtdeVagas'] ?></p>
    <p><b>Horário de Trabalho:</b> <?php echo $vaga['horarioTrabalho'] ?></p>
    <p><b>Tipo de Contrato:</b> <?php echo $vaga['tipoContrato'] ?></p>
    <p><b>Salário:</b> <?php echo $vaga['salario'] ?></p>
    <p><b>Vaga Cadastrada em:</b> <?php echo $vaga['dataCadastro'] ?></p>
    <p><b>Status da Vaga:</b> <?php if 
        ($vaga['statusVaga']=='N')echo "Não Iniciado";
        else if ($vaga['statusVaga']=='A')echo "Aberta";
        else if ($vaga['statusVaga']=='EA')echo "Em Andamento";
        else if ($vaga['statusVaga']=='P')echo "Pausado"; ?></p>
    <div class="center-content">
        <button name="candidatar" class="newVaga" id='editarVaga'>Editar vaga</button>
    </div>
</div>

<form method="POST" class="center-content">
    <button class="newVaga" name="cancelarVaga" value="<?php $id ?>">Cancelar Vaga</button>
</form>

<div class="dados">
    <form method="POST" class="container-hidden" id='editarVaga'>
        <div>
            <input type="hidden" name="id" readonly placeholder="<?php echo $id ?>">
            <div><span>Aréa Interesse</span><input type="text" name="areaInteresse" required placeholder="<?php echo $vaga['FK_Id_areainteresse'] ?>"></div>
            <div><span>Cargo</span><input type="text" name="cargo" required placeholder="<?php echo $vaga['cargo'] ?>"></div>
            <div><span>Descrição da Vaga</span><input type="textarea" name="descricao" required placeholder="<?php echo $vaga['descricao'] ?>"></div>
            <div><span>Quantidade de Vagas Disponíveis</span><input type="text" name="qtdeVagas" required placeholder="<?php echo $vaga['qtdeVagas'] ?>"></div>
            <div><span>Horário de Trabalho</span><input type="text" name="horarioTrabalho" placeholder="<?php echo $vaga['horarioTrabalho'] ?>"></div>
            <div><span>Tipo de Contrato</span><input type="text" name="tipoContrato" placeholder="<?php echo $vaga['tipoContrato'] ?>"></div>
            <div><span>Salário</span><input type="text" name="salario" placeholder="<?php echo $vaga['salario'] ?>"></div>
            <div><span>Detalhes da Vaga</span><input type="text" name="salario" placeholder="<?php echo $vaga['detalhesVaga'] ?>"></div>
            <div><span>Data</span><input type="text" name="salario" placeholder="<?php echo $vaga['dataCadastro'] ?>"></div>
            <div><span>Status</span><input type="text" name="detalhes" placeholder="<?php echo $vaga['statusVaga'] ?>"></div>
        </div>
        <div class="center-content">
            <input class="submit" name="botao" type="submit" value="Salvar Alterações">
        </div>
        <?php if(!empty($error)){?>
            <div class="error"><?php echo $error ?></div>
        <?php } ?>
    </form> 

</div>