<h1 class="title">Analistas - Empresa: <?php echo $_SESSION['Id_empresa'] ?></h1>
<?php
    if(!empty($analistas)){
        foreach($analistas as $a){ ?>
            <div class="overflow-x">
                <table class="tabela">
                    <tr>
                        <th>Nome</th>
                        <th>E-mail</th>
                        <th>Ações</th>
                    </tr>
                    <tr>
                        <td><?= $a['nome']?></td>
                        <td><?= $a['email'] ?></td>
                        <td>
                            <button class="newVaga" id="inserirAnalista">Editar Analista</button>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="center-content">
                <button class="newVaga" id="inserirAnalista" value="novo">Novo Usuário</button><br><br>
            </div>
        <?php }
    }else { ?>
        <p>No momento não há analistas cadastrados</p>
        <div class="center-content">
            <button class="newVaga" id="inserirAnalista">Novo analista</button>
        </div>
    <?php } ?>

<div class="dados">
    <form method="POST" id="inserirAnalista" class="container-hidden">
        <div>
            <div><span>Nome:</span><input type="text" name="nome_user" required placeholder="Nome Completo: "></div>
            <div><span>Email:</span><input type="text" name="email_user" required placeholder="E-mail: "></div>
            <div><span>Login:</span> <input type="text" name="login" required placeholder="Login: "></div>
            <div><span>Senha:</span><input type="password" name="senha" required placeholder="Senha: "></div>
        </div>
        <div class="center-content">
            <input type="submit" value="Registrar">
        </div>
        <div class="error"><?= $error ?>
    </form>
</div>