<?php
    echo "<h4>Analistas Cadastrados:</h4>";
    print_r($result);
    foreach($result as $ac){
        echo $ac."<br>";
    }
?>
<form method="POST" id="form-register">
    <h1>Registrar Analista</h1>
    <input type="text" name="login" required placeholder="Login: ">
    <input type="password" name="senha" required placeholder="Senha: "><br>
    <input type="submit" value="Registrar">
    <div class="error"><?= $error ?></div>
</form>