<br><h2 align="center">Vagas Cadastradas</h2><br>
<button class="newVaga" value="novo" id="novavaga">Nova Vaga</button><br><br>

<!--<strong><a>Filtrar por: </a></strong><br>
<a>Cargo:<input type="text" name="filtro" required placeholder="Digite aqui sua busca... "></a>
<a>Área de Interesse:
    <select name="opcaofiltro">
        <option value="1">Administração</option>
        <option value="2">Química</option>
        <option value="3">Ciências Exatas</option>
    </select>
</a>
<input type="text" name="filtro" required placeholder="Digite aqui sua busca... ">
<a>Situação da Vaga:</a>
<select name="opcaofiltro">
    <option value="1">Não Iniciada</option>
    <option value="1">Aberta</option>
    <option value="2">Em Andamento</option>
    <option value="3">Concluída</option>
</select>
<button>Pesquisar</button>-->

<table align="center">
    <tr align="center">
        <td>ID Vaga</td>
        <td>Area Interesse</td>
        <td>Cargo</td>
        <td>Qtde. Vagas</td>
        <td>Salário</td>
        <td>Data Cadastro</td>
        <td>Detalhes da Vaga</td>
        <td>Situação</td>
        <td>Ações</td>
    </tr>
    <?php foreach($vagas as $v){ ?>
        <tr align="center">
            <td><?php echo $v['ID_vaga'] ?></td>
            <td><?php echo $v['areainteresse'] ?></td>
            <td><?php echo $v['cargo'] ?></td>
            <td><?php echo $v['qtdeVagas'] ?></td>
            <td><?php echo $v['salario'] ?></td>
            <td><?php echo $v['dataCadastro'] ?></td>
            <td><?php echo $v['detalhesVaga'] ?></td>
            <td><?php 
                if ($v['statusVaga']=='N')echo "Não Iniciado";
                else if ($v['statusVaga']=='A')echo "Aberta";
                else if ($v['statusVaga']=='EA')echo "Em Andamento";
                else if ($v['statusVaga']=='P')echo "Pausado";
            ?></td>
            <td>
                <form method="POST">
                    <button name="detalhesTemp" value="<?php echo $v['ID_vaga'] ?>">Detalhes</button>
                </form>
            </td>
        </tr>
    <?php } ?>
</table>

<form method="POST" class="container" id="novavaga">
    <h1>Vaga</h1>
    <input type="text" name="id" readonly placeholder="id: ">
    <input type="text" name="areaInteresse" required placeholder="areainteresse: ">
    <input type="text" name="cargo" required placeholder="cargo: ">
    <input type="text" name="descricao" required placeholder="descricao: ">
    <input type="text" name="qtdeVagas" required placeholder="qtdeVagas: ">
    <input type="text" name="horarioTrabalho" placeholder="horarioTrabalho: ">
    <input type="text" name="tipoContrato" placeholder="tipoContrato: ">
    <input type="text" name="salario" placeholder="salario: ">
    <input type="text" name="detalhes" placeholder="detalhesVaga: ">
    <!--<input type="text" name="id_vaga">
    <input type="text" name="id_vaga">-->
    <input class="submit" name="botao" type="submit" value="Adicionar">
    <?php if(!empty($error)){?>
        <div class="error"><?php echo $error ?></div>
    <?php } ?>
    <br>
</form> 
