<br><br>
<button>Nova Vaga</button>

<table class="table table-striped table-bordered">
    </br></br></br>
    <tr>
        <td align="center">ID Vaga</td>
        <td align="center">Cargo</td>
        <td align="center">Qtde Vagas</td>
        <td align="center">Ações</td>
    </tr>
    
    <?php if ($vagas) {
        foreach ($vagas as $v){?>
            <tr>
                <td align="center"><?= $v['Id_vaga']?></td>
                <td><?= $v['cargo'] ?></td>
                <td align="center"><?= $v['qtdevagas'] ?></td>
                <td align="center">
                    <button class="candidatar btn btn-primary" value="<?= $v['Id_vaga'] ?>">
                        Editar
                    </button>
                    <button class="candidatar btn btn-primary" value="<?= $v['Id_vaga'] ?>">
                        Remover
                    </button>
                    
                </td>
            </tr>
            <?php
        }
    }else {
        echo "<tr>" . "No momento não há vagas Disponíveis para estas Areas de Interesse" . "</tr>";
    }?>	
</table>

<br><br>
