<h1 class="title">Alterar Informações de Meu Perfil de Acesso</h1>
<div class="inform">
    <p><b>Nome Completo:</b> <?php echo $dadosconta['nome_completo'] ?></p>
    <p><b>E-mail:</b> <?php echo $dadosconta['email'] ?></p>
    <p><b>CPF:</b> <?php echo $dadosconta['cpf'] ?></p>
</div>

<div class="dados">
  <form method="POST" enctype="multipart/form-data">
      <label>Foto:</label>
      <input type="file" name="foto" />
      <input type="submit" value="Salvar" />
  </form>
</div>

<div class="center-content">
    <button class="newVaga" id="alterarSenhaAcesso">Alterar Senha de Acesso</button></a>
</div>
<div class="dados">
  <form method="POST" id="alterarSenhaAcesso" class="container-hidden">
      <div>
      <input type="hidden" name="nome" required placeholder="<?php echo $dadosconta['nome_completo'] ?>" disabled>
      <input type="hidden" name="email" required placeholder="<?php echo $dadosconta['email'] ?>" disabled>
      <input type="hidden" name="cpf" required placeholder="<?php echo $dadosconta['cpf'] ?>" disabled>
      <div><span>Nova Senha:</span><input type="password" name="password" required placeholder="Insira sua nova Senha... "></div>
      <div><span>Confirme a Senha:</span><input type="password" name="password" required placeholder="Confirme sua nova Senha... "></div>
      </div>
      <div class="center-content">
          <button>Salvar Nova Senha</button>
      </div>
  </form>
</div>