<br><br><h3 align="center">Alterar Informações de Meu Perfil de Acesso</h3>
<br><br>
<form method="POST" enctype="multipart/form-data">
  <label>Foto:</label>
  <input type="file" name="foto" />
  <input type="submit" value="Salvar" />
</form>

<form method="POST" id="alterarSenha">
    Nome: <input type="text" name="nome" required placeholder="<?php echo $dadosconta['nome_completo'] ?>" disabled>
    E-mail: <input type="text" name="email" required placeholder="<?php echo $dadosconta['email'] ?>" disabled>
    CPF: <input type="text" name="cpf" required placeholder="<?php echo $dadosconta['cpf'] ?>" disabled>
    <input type="password" name="password" required placeholder="Insira sua nova Senha... ">
    <input type="password" name="password" required placeholder="Confirme sua nova Senha... ">
    <button>Alterar Senha</button>
    <br>
</form>