<?php
echo "<h4>Dados Pessoais:</h4>";
?>

<table>
    <tr class="grow-tr"   >
        <td class="grow-td">ID</td>
        <td class="grow-td">Nome</td>
        <td class="grow-td">CPF</td>
        <td class="grow-td">E-mail</td>
        <td class="grow-td">Ações</td>
    </tr>
    
    <?php if (!empty($dadoPessoal)) {
            ?>
            <tr>
                <td class="grow-td"><?= $dadoPessoal['Id_candidato']?></td>
                <td class="grow-td"><?= $dadoPessoal['nome_completo'] ?></td>
                <td class="grow-td"><?= $dadoPessoal['cpf'] ?></td>
                <td class="grow-td"><?= $dadoPessoal['email'] ?></td>
                <td class="grow-td">
                    <button class="newVaga" id="dadoPessoal" value="<?php $dadoPessoal['Id_candidato'] ?>">Editar Dados Pessoais</button><br><br>
                </td>
            </tr>
            <?php
    }else {
        echo "<tr>" . "No momento não há Dados Cadastrados em seu Currículo" . "</tr>";
    }
    //endif;
    ?>	
</table>
<form method="POST" id="dadoPessoal" class="container">
    <h1>Dados Pessoais</h1>
    <input type="text" name="nome" value="<?php echo $dadoPessoal['nome_completo']?>" required placeholder="Nome... ">
    <input type="text" name="cpf" value="<?php echo $dadoPessoal['cpf']?>" required placeholder="CPF... "><br>
    <input type="text" name="rg" value="<?php echo $dadoPessoal['rg']?>" required placeholder="RG... ">
    <input type="text" name="orgao_emissor" value="<?php echo $dadoPessoal['orgao_emissor']?>" required placeholder="Orgão Emissor... ">
    <input type="date" name="data_expedicao" value="<?php echo $dadoPessoal['data_expedicao']?>" required placeholder="Data Expedição... ">
    <input type="text" name="sexo" value="<?php echo $dadoPessoal['sexo']?>"required placeholder="Sexo... ">
    <input align=center type="date" name="data_nascimento" value="<?php echo $dadoPessoal['data_nascimento']?>" required placeholder="Data Nascimento... ">
    <input type="text" name="estado_civil" value="<?php echo $dadoPessoal['estado_civil']?>" required placeholder="Estado Civil... ">
    <input type="text" name="email" value="<?php echo $dadoPessoal['email']?>" required placeholder="Email... "><br>
    <input type="text" name="nome_pai" value="<?php echo $dadoPessoal['nome_pai']?>" required placeholder="Nome do Pai... ">
    <input type="text" name="nome_mae" value="<?php echo $dadoPessoal['nome_mae']?>" required placeholder="Nome da Mãe... ">
    <input type="text" name="endereco" value="<?php echo $dadoPessoal['endereco']?>" required placeholder="Endereço... ">
    <input type="text" name="bairro" value="<?php echo $dadoPessoal['bairro']?>" required placeholder="Bairro... ">
    <input type="text" name="regiao" value="<?php echo $dadoPessoal['regiao']?>" required placeholder="Região... ">
    <input type="text" name="cidade" value="<?php echo $dadoPessoal['cidade']?>" required placeholder="Cidade... ">
    <input type="text" name="cep" value="<?php echo $dadoPessoal['cep']?>" required placeholder="CEP... ">
    <input type="text" name="estado" value="<?php echo $dadoPessoal['estado']?>" required placeholder="Estado... ">
    <input type="text" name="telefone" value="<?php echo $dadoPessoal['telefone']?>"required placeholder="Telefone... ">
    <input type="text" name="celular" value="<?php echo $dadoPessoal['celular']?>"required placeholder="Celular... ">
    <input type="text" name="id_user" value="<?php echo $dadoPessoal['FK_Id_user']?>"required placeholder="ID User... " disabled>
    <input type="submit" value="Salvar">
    <div class="error"><?= $error ?></div>
</form>

<?php
echo "<h4>Dados Profissionais:</h4>";
//print_r($dadoProfissional);
echo "Resumo Profissional: ".$dadoProfissional['resumoprofissional']."<br>";
echo "Objetivo Profissional: ".$dadoProfissional['objetivoprofissional']."<br><br>";

?>

<button class="newVaga" id="dadoProfissional" value="<?php $dadoPessoal['Id_candidato'] ?>">Editar Dados Profissionais</button><br><br>
<form method="POST" id="dadoProfissional" class="container">
    <input type="text" name="resumoprofissional" required placeholder="Resumo Profissional... "><br>
    <input type="text" name="objetivoprofissional" required placeholder="Objetivo Profissional... "><br>
    <input type="submit" value="Salvar">
</form>


<?php
echo $teste;
echo "<h4>Área de Interesse:</h4>";
?>
<table class="table table-striped table-bordered">
    <tr>
        <td align="center">ID Área Interesse</td>
        <td align="center">Descrição</td>
        <td align="center">Ações</td>
    </tr>
    
    <?php if ($areaInteresseCandidato) {
        foreach ($areaInteresseCandidato as $ai){?>
            <tr>
                <td align="center"><?= $ai['FK_Id_areainteresse']?></td>
                <td><?= $ai['descricao'] ?></td>
                <td align="center">
                    <a class="btn btn-primary"
                       href="dashboard?id=<?= $ai['FK_Id_areainteresse'] ?>">
                        Remover
                    </a>
                </td>
            </tr>
            <?php
        }
    }else {
        echo "<tr>" . "No momento não há vagas Disponíveis para estas Areas de Interesse" . "</tr>";
    }?>	
</table>
<button class="newVaga" id="areaInteresse" value="<?php $dadoPessoal['Id_candidato'] ?>">Adicionar Área Interesse</button><br><br>
<form method="POST" id="areaInteresse" class="container">
    <h1>Áreas de Interesse</h1>
    <select name="areaInteresse">
        <?php foreach ($areaInteresse as $ai){ ?>
                    <option value="<?php echo $ai['ID_areainteresse']?>"> <?php echo $ai['descricao']?></option>
        <?php } ?>
    </select>
    <input type="submit" value="Salvar">
    <div class="error"><?= $error ?></div>
</form>

<?php
echo "<h4>Redes Sociais:</h4>";
//print_r($redeSocial);
?>
<table class="table table-striped table-bordered">
    </br>
    <tr>
        <td align="center">ID Rede Social</td>
        <td align="center">Rede Social</td>
        <td align="center">Link</td>
        <td align="center">Ações</td>
    </tr>
    
    <?php if ($redeSocial) {
        foreach ($redeSocial as $rs){?>
            <tr>
                <td align="center"><?= $rs['Id_redesocialcandidato']?></td>
                <td><?= $rs['redesocial'] ?></td>
                <td><?= $rs['link_redesocial'] ?></td>
                <td align="center">
                    <a class="btn btn-primary"
                       href="dashboard?id=<?= $rs['Id_redesocialcandidato'] ?>">
                        Remover
                    </a>
                </td>
            </tr>
            <?php
        }
    }else {
        echo "<tr>" . "No momento não há vagas Disponíveis para estas Areas de Interesse" . "</tr>";
    }?>	
</table>
<button class="newVaga" id="redeSocial" value="<?php $dadoPessoal['Id_candidato'] ?>">Adicionar Rede Social</button><br><br>
<form method="POST" id="redeSocial" class="container">
    <h1>Redes Sociais</h1>
    <select name="redesocial">
        <option value="Facebook">Facebook</option>
        <option value="Instagram">Instagram</option>
        <option value="Twitter">Twitter</option>
        <option value="Linkedin">Linkedin</option>
    </select>
    
    <input type="text" name="link_redesocial" required placeholder="Link de Acesso... "><br>
    <input type="submit" value="Salvar">
    <div class="error"><?= $error ?></div>
</form>

<?php
echo "<h4>Dados Complementares:</h4>";
echo "Tipo Habilitação: ".$dadoComplementar['tipohabilitacao']."  -  Nº Habilitação: ".$dadoComplementar['numerocnh']."<br>";
echo "Carteira de Trabalho Nº: ".$dadoComplementar['carteiratrabalho']."  -  Carteira Militar Nº: ".$dadoComplementar['carteiramilitar']."<br>";
echo "Editar Dados<br>Remover Dados<br>";

//print_r($dadoComplementar);
?>
<button class="newVaga" id="dadoComplementar" value="<?php $dadoPessoal['Id_candidato'] ?>">Editar Dados Complementares</button><br><br>
<form method="POST" id="dadoComplementar" class="container">
    <h1>Dados Complementares</h1>
    <select name="tphabilitacao">
        <option value="Tipo A">Tipo A</option>
        <option value="Tipo B">Tipo B</option>
        <option value="Tipo C">Tipo C</option>
        <option value="Tipo D">Tipo D</option>
        <option value="Tipo E">Tipo E</option>
    </select>
    <input type="text" name="numerocnh" required placeholder="Número CNH... "><br>
    <input type="text" name="carteiraTrabalho" required placeholder="Carteira de Trabalho... "><br>
    <input type="text" name="carteiraMilitar" required placeholder="Carteira Militar... "><br>
    <input type="submit" value="Salvar">
    <div class="error"><?= $error ?></div>
</form>

<?php
echo "<h4>Formação Acadêmica:</h4>";
//print_r($formacao);
?>
<table class="table table-striped table-bordered">
    </br>
    <tr>
        <td align="center">ID Formação</td>
        <td align="center">Curso</td>
        <td align="center">Instituição</td>
        <td align="center">Situação</td>
        <td align="center">Data Inicio</td>
        <td align="center">Data Término</td>
        <td align="center">Ações</td>
    </tr>
    
    <?php if ($formacao) {
        foreach ($formacao as $f){?>
            <tr>
                <td align="center"><?= $f['Id_formacaoacademica']?></td>
                <td><?= $f['curso'] ?></td>
                <td><?= $f['instituicao'] ?></td>
                <td><?= $f['situacao'] ?></td>
                <td><?= $f['dataInicio'] ?></td>
                <td><?= $f['dataFim'] ?></td>
                <td align="center">
                    <button class="newVaga" id="formacao" value="<?php $dadoPessoal['Id_candidato'] ?>">Editar Formação Acadêmica</button><br><br>
                </td>
            </tr>
            <?php
        }
    }else {
        echo "<tr>" . "No momento não há vagas Disponíveis para estas Areas de Interesse" . "</tr>";
    }?>	
</table>

<button class="newVaga" id="formacao" value="<?php $dadoPessoal['Id_candidato'] ?>">Nova Formação Acadêmica</button><br><br>
<form method="POST" id="formacao" class="container">
    <h1>Formação Acadêmica</h1>
    <input type="text" name="curso" required placeholder="Curso... "><br>
    <input type="text" name="instituicao" required placeholder="Instituição de Ensino... "><br>
    <select name="situacao">
        <option value="Concluido">Concluído</option>
        <option value="Cursando">Cursando</option>
        <option value="Pausado">Pausado</option>
    </select>
    <input type="date" name="dataInicio" required placeholder="Data de Início... "><br>
    <input type="date" name="dataFim" required placeholder="Data de Finalização... "><br>
    <input type="date" name="previsaoTermino" required placeholder="Previsão de Término... "><br>
    <input type="submit" value="Salvar">
    <div class="error"><?= $error ?></div>
</form>

<?php
echo "<h4>Idiomas:</h4>";
?>
<table class="table table-striped table-bordered">
    </br>
    <tr>
        <td align="center">ID Idioma</td>
        <td align="center">Idioma</td>
        <td align="center">Nível</td>
        <td align="center">Ações</td>
    </tr>
    
    <?php if ($idioma) {
        foreach ($idioma as $i){?>
            <tr>
                <td align="center"><?= $i['Id_idioma']?></td>
                <td><?= $i['idioma'] ?></td>
                <td><?= $i['nivel'] ?></td>
                <td align="center">
                    <a class="btn btn-primary"
                       href="dashboard?id=<?= $i['Id_idioma'] ?>">
                        Editar Dados
                    </a>
                </td>
                <td align="center">
                    <a class="btn btn-primary"
                       href="dashboard?id=<?= $i['Id_idioma'] ?>">
                        Remover
                    </a>
                </td>
            </tr>
            <?php
        }
    }else {
        echo "<tr>" . "No momento não há vagas Disponíveis para estas Areas de Interesse" . "</tr>";
    }?>	
</table>

<button class="newVaga" id="idioma" value="<?php $dadoPessoal['Id_candidato'] ?>">Adicionar Idioma</button><br><br>
<form method="POST" id="idioma" class="container">
    <h1>Idiomas</h1>
    <input type="text" name="idioma" required placeholder="Idioma... "><br>
    <select name="nivel">
        <option value="Básico">Básico</option>
        <option value="Intermediário">Intermediário</option>
        <option value="Avançado">Avançado</option>
    </select>
    <input type="submit" value="Salvar">
    <div class="error"><?= $error ?></div>
</form>

<?php
echo "<h4>Conhecimentos:</h4>";
echo "Conhecimentos do Candidato: ".$conhecimento['conhecimento'];
//print_r($conhecimento);
?>
<button class="newVaga" id="conhecimentos" value="<?php $dadoPessoal['Id_candidato'] ?>">Editar Conhecimentos</button><br><br>
<form method="POST" id="conhecimentos" class="container">
    <h1>Conhecimentos</h1>
    <input type="text" name="conhecimento" required placeholder="Conhecimentos... ">
    <input type="submit" value="Salvar">
    <div class="error"><?= $error ?></div>
</form>

<?php
echo "<h4>Experiências Profissionais:</h4>";
//print_r($experiencia);
?>
<table class="table table-striped table-bordered">
    </br>
    <tr>
        <td align="center">ID Experiência</td>
        <td align="center">Empresa</td>
        <td align="center">Cargo</td>
        <td align="center">Ações</td>
    </tr>
    
    <?php if ($experiencia) {
        foreach ($experiencia as $e){?>
            <tr>
                <td align="center"><?= $e['Id_experienciaprofissional']?></td>
                <td><?= $e['empresa'] ?></td>
                <td><?= $e['cargo'] ?></td>
                <td class='lasttd' align="center">
                    <button class="newVaga" id="experiencia" value="<?php $dadoPessoal['Id_candidato'] ?>">Editar Experiência</button><br><br>
                    
                    <div class="delete btn btn-primary" data-value="<?= $e['Id_experienciaprofissional'] ?>">
                        Remover
                    </div>
                </td>
            </tr>
            <?php
        }
    }else {
        echo "<tr>" . "No momento não há vagas Disponíveis para estas Areas de Interesse" . "</tr>";
    }?>	
</table>
<button class="newVaga" id="experiencia" value="novo">Adicinonar Experiência Profissional</button><br><br>
<form method="POST" id="experiencia" class="container">
    <h1>Experiência Profissional</h1>
    <!--<input type="hidden" name='id' value='0'> -->
    <input type="text" name="empresa" required placeholder="Empresa... " value=''><br>
    <input type="date" name="dataAdmissao" required placeholder="... " value=''><br>
        <input type="date" name="dataDemissao" required placeholder="... " value=''><br>
    <input type="text" name="cargo" required placeholder="Cargo... " value=''><br>
    <input type="text" name="atualEmprego" required placeholder="Atual Emprego... " value=''><br>
     
    <select name="areaTrabalho">
        <?php foreach ($areaInteresse as $ai){ ?>
                    <option value="<?php echo $ai['ID_areainteresse']?>"> <?php echo $ai['descricao']?></option>
        <?php } ?>
    </select>
    <input type="textarea" name="atividadesExercidas" required placeholder="Atividades Exercidas... " value=''><br>
    <input type="submit" value="Salvar">
    <div class="error"><?= $error ?></div>
</form>






