
<?php
    echo "<h3>".$_SESSION['username'].", Bem Vindo ao EmpregaBR</h3>";
    echo "<br>Id User: ".$_SESSION['Id_user'];
    echo "<br>Level User: ".$_SESSION['level'];
    echo "<br>Id Candidato: ".$_SESSION['Id_candidato']."<br><br>";
    
?>

<div id="feedback">
    <h2 align=center>Histórico de Feedbacks</h2>
    <button>Área dos Feedbacks</button><br>
</div>
<br>
<div id="indique">
    <h2 align=center>Indique a um Amigo</h2>
    <button>Indique a um Amigo</button>
</div>
<br>




