<h2 class="title">Dashboard Cliente: <?php echo $_SESSION['username'].", Bem Vindo ao EmpregaBR" ?></h2>

<div id="feedback">
    <h2>Histórico de Feedbacks</h2>
    <form method="POST">
        <button name="+processosseletivos">Area dos Feedbacks</button>
    </form>
</div>
<br>
<div id="indique">
    <h2 align=center>Indique a um Amigo</h2>
    <form method="POST">
        <button name="+processosseletivos">Indique um amigo</button>
    </form>
</div>
<br>




