Página de Processos Seletivos Ativos<br><br>
Teste

<?php
//print_r($processosativos);

foreach ($processosativos as $pa){
    echo "Processo Seletivo Nº: ".$pa['ID_processoseletivo']."<br>";
    echo "Vaga Nº: ".$pa['FK_Id_vaga']."<br>";
    echo "Cargo: ".$pa['cargo']."<br>";
    echo "Status do Processo Seletivo: ".$pa['status']."<br>";
    echo "Vagas Restantes: ".$pa['vagasrestantes']."<br>";
    echo "Empresa: ".$pa['FK_Id_empresa']."<br><br>";
}
?>

