<h1 class="title">Vaga <?php echo $vaga['cargo'] ?></h1>
<div class="template">
    <p><b>Vaga Nº:</b> <?php echo $id ?></p>
    <p><b>Vaga:</b> <?php echo $vaga['cargo'] ?></p>
    <p><b>Área de Interesse:</b> <?php echo $vaga['areainteresse'] ?></p>
    <p><b>Descrição da Vaga:</b> <?php echo $vaga['descricao'] ?></p>
    <p><b>Quantidade de Vagas Disponíveis:</b> <?php echo $vaga['qtdeVagas'] ?></p>
    <p><b>Horário de Trabalho:</b> <?php echo $vaga['horarioTrabalho'] ?></p>
    <p><b>Tipo de Contrato:</b> <?php echo $vaga['tipoContrato'] ?></p>
    <p><b>Salário:</b> <?php echo $vaga['salario'] ?></p>
    <p><b>Vaga Cadastrada em:</b> <?php echo $vaga['dataCadastro'] ?></p>
    <p><b>Status da Vaga:</b> <?php if 
        ($vaga['statusVaga']=='N')echo "Não Iniciado";
        else if ($vaga['statusVaga']=='A')echo "Aberta";
        else if ($vaga['statusVaga']=='EA')echo "Em Andamento";
        else if ($vaga['statusVaga']=='P')echo "Pausado"; ?></p>
    
    <form method="POST">
        <button name="candidatar" class="newVaga">Candidatar-Me</button><br><br>
    </form>    
</div>

<!--<form method="POST" class="container">
    <h1>Vaga</h1>
    <input type="text" name="id" readonly placeholder="<?php /*echo $id ?>">
    <input type="text" name="areaInteresse" required placeholder="<?php echo $vaga['FK_Id_areainteresse'] ?>">
    <input type="text" name="cargo" required placeholder="<?php echo $vaga['cargo'] ?>">
    <input type="textarea" name="descricao" required placeholder="<?php echo $vaga['descricao'] ?>">
    <input type="text" name="qtdeVagas" required placeholder="<?php echo $vaga['qtdeVagas'] ?>">
    <input type="text" name="horarioTrabalho" placeholder="<?php echo $vaga['horarioTrabalho'] ?>">
    <input type="text" name="tipoContrato" placeholder="<?php echo $vaga['tipoContrato'] ?>">
    <input type="text" name="salario" placeholder="<?php echo $vaga['salario'] ?>">
    <input type="text" name="salario" placeholder="<?php echo $vaga['detalhesVaga'] ?>">
    <input type="text" name="salario" placeholder="<?php echo $vaga['dataCadastro'] ?>">
    <input type="text" name="detalhes" placeholder="<?php echo $vaga['statusVaga'] ?>">
    <input class="submit" name="botao" type="submit" value="Salvar Alterações">
    <?php if(!empty($error)){?>
        <div class="error"><?php echo $error ?></div>
    <?php } ?>
</form> 


<form method="POST">
    <button name="cancelarVaga" value="<?php $id */?>">Cancelar Vaga</button>
</form>        
        
-->
