<br><strong><a>Selecione o Filtro Desejado</a></strong>
<select name="opcaofiltro">
        <option value="1">Cargo</option>
        <option value="2">Localidade</option>
        <option value="3">Status</option>
</select>
<input type="text" name="filtro" required placeholder="Digite aqui sua busca... ">
<button>Pesquisar</button>

<table class="table table-striped table-bordered">
    </br></br></br>
    <tr>
        <td align="center">ID Vaga</td>
        <td align="center">Empresa</td>
        <td align="center">Cargo</td>
        <td align="center">Qtde Vagas</td>
        <td align="center">Data Cadastro</td>
        <td align="center">Status</td>
        <td align="center">Ações</td>
    </tr>
    
    <?php if ($vagas) {
        foreach ($vagas as $v){?>
            <tr>
                <td align="center"><?= $v['ID_vaga']?></td>
                <td align="center"><?= $v['nomeFantasia']?></td>
                <td><?= $v['cargo'] ?></td>
                <td align="center"><?= $v['qtdeVagas'] ?></td>
                <td align="center"><?php echo date('d/m/Y', strtotime($v['dataCadastro'])) ?></td>
                <td>
                    <?php 
                        if ($v['statusVaga']=='N')echo "Não Iniciado";
                        else if ($v['statusVaga']=='A')echo "Aberta";
                        else if ($v['statusVaga']=='EA')echo "Em Andamento";
                        else if ($v['statusVaga']=='P')echo "Pausado";
                    ?>
                </td>
                <td>
                    <form method="POST">
                        <button name="detalhesTemp" value="<?php echo $v['ID_vaga'] ?>">Detalhes</button>
                    </form>
                </td>
            </tr>
            <?php
        }
    }else {
        echo "<tr>" . "No momento não há vagas Disponíveis para estas Areas de Interesse" . "</tr>";
    }?>	
</table>

<br><br>