<h1 class="title">Vagas</h1>

<div class="filtro">
    <strong>Selecione o Filtro Desejado:</strong>
    <select name="opcaofiltro">
            <option value="1">Cargo</option>
            <option value="2">Localidade</option>
            <option value="3">Status</option>
    </select>
    <input type="text" name="filtro" required placeholder="Digite aqui sua busca... ">
    <button>Pesquisar</button>
</div>

<?php if (!empty($vagas)) { ?>
<div class="overflow-x">
    <table class="tabela">
        <tr>
            <th>ID Vaga</th>
            <th>Empresa</th>
            <th>Cargo</th>
            <th>Qtde Vagas</th>
            <th>Data Cadastro</th>
            <th>Status</th>
            <th>Ações</th>
        </tr>

        <?php foreach ($vagas as $v){?>
                <tr>
                    <td><?= $v['ID_vaga']?></td>
                    <td><?= $v['nomeFantasia']?></td>
                    <td><?= $v['cargo'] ?></td>
                    <td><?= $v['qtdeVagas'] ?></td>
                    <td><?php echo date('d/m/Y', strtotime($v['dataCadastro'])) ?></td>
                    <td>
                        <?php 
                            if ($v['statusVaga']=='N')echo "Não Iniciado";
                            else if ($v['statusVaga']=='A')echo "Aberta";
                            else if ($v['statusVaga']=='EA')echo "Em Andamento";
                            else if ($v['statusVaga']=='P')echo "Pausado";
                        ?>
                    </td>
                    <td>
                        <form method="POST">
                            <button name="detalhesTemp" value="<?php echo $v['ID_vaga'] ?>">Detalhes</button>
                        </form>
                    </td>
                </tr>
                <?php
            }
        }else { ?>
            <p>Não existe nenhuma vaga ainda.</p>
        <?php } ?>	
    </table>
</div>